spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cargo
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: CargoHikariCP

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Или none, если миграции через Flyway/Liquibase
    properties:
      hibernate:
        format_sql: true
        show_sql: true  # Показывать SQL в логах
        jdbc:
          batch_size: 50
        envers:
          default_schema: aud
          store_data_at_delete: true
    open-in-view: false  # Закрывать сессию после выполнения запроса

  logging:
    level:
      org.hibernate.SQL: DEBUG  # Логирование SQL-запросов
      org.hibernate.type.descriptor.sql: TRACE  # Вывод значений параметров

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    check-template-location: true
    settings:
      number_format: computer
